### PR TITLE
fix write method in product profile

### PR DESCRIPTION
**Pull request by chafique-delli**
I think we should rather update in the products, the settings that have been changed in the profile, and not rewrite the profile on the products.

### CODE REVIEW

**Comment by hparfr** [comment]
If you update profile.explanation you want to write product.explanation ?

**Comment by hparfr** [comment]
Btw, what do you want to _fix_ ?

**Comment by chafique-delli** [comment]
@hparfr , the 'explanation' field on the product is a related field from profile.

**Comment by chafique-delli** [comment]
@hparfr , Fields that are relevant to the profile are excluded from the product update (ex. explanation, name, sequence, display_name, ..)

**Pull request closed without merging**
